[project]
name = "dbc-polars-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "adbc-driver-manager>=1.8.0",
    "dbc>=0.1.0",
    "polars>=1.35.1",
    "pyarrow>=22.0.0",
    "rich>=14.2.0",
]
